<?php
/********************************************************************************
* Subs-Aeva-Generated-Sites.php v6
* By Rene-Gilles Deberdt (created by Karl Benson)
*********************************************************************************
* The full/complete definitions are now stored in Subs-Aeva-Sites.php
* This is a GENERATED php file containing ONLY ENABLED sites for the Aeva Mod,
* and is created when enabling/disabling sites via the admin panel.
* It's more efficient this way.
*********************************************************************************
* This program is distributed in the hope that it is and will be useful, but
* WITHOUT ANY WARRANTIES; without even any implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE.
********************************************************************************/

global $sites;
$sites = array(
	array(
		'id' => 'ytb',
		'pattern' => 'http://(?:video\.google\.(?:com|com?\.[a-z]{2}|[a-z]{2})/[^"]*?)?(?:(?:www|[a-z]{2})\.)?youtu(?:be\.com/[^"#[]*?(?:[&/?;]|&amp;|%[23]F)(?:video_id=|v(?:/|=|%3D|%2F))|\.be/)([\w-]{11})',
		'movie' => 'http://www.youtube.com/v/$2&rel=0&fs=1',
		'size' => array('normal' => array(480, 385), 'ws' => array(640, 385)),
		'ui-height' => 25,
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="http://www\.youtube\.com/v/([\w-]{11})(?:&[^"]*)?">.*?</object>',
		'fix-html-url' => 'http://www.youtube.com/watch?v=$1',
		'lookup-url' => 'http://(?:video\.google\.(?:com|com?\.[a-z]{2}|[a-z]{2})/[^"]*?)?(?:(?:www|[a-z]{2})\.)?youtube\.com/[^"#[]*?(?:[&/?;]|&amp;|%[23]F)(?:video_id=|v(?:/|=|%3D|%2F))([\w-]{11})[^]#[]*',
		'lookup-actual-url' => 'http://gdata.youtube.com/feeds/api/videos/$1?v=2',
		'lookup-final-url' => 'http://www.youtube.com/watch?v=$1',
		'lookup-title' => true,
		'lookup-title-skip' => true,
		'lookup-pattern' => array('id' => '<id>.*?:([\w-]+)</id>', 'error' => '<internalReason>(.*?)</internalReason>', 'noexternalembed' => '<yt:accessControl\saction=\'embed\'\spermission=\'denied\'/>', 'ws' => '<yt:aspectRatio>widescreen</yt:aspectRatio>'),
	),
	array(
		'id' => 'ytp',
		'pattern' => 'http://(?:(?:www|[a-z]{2})\.)?youtube\.com/[^"]*?(?:[&/?;]|&amp;)(?:id=|p=|p/)([0-9a-f]{16})',
		'movie' => 'http://www.youtube.com/p/$2&rel=0&fs=1',
		'size' => array(480, 385),
		'ui-height' => 25,
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="$1" />.*?</object>',
	),
	array(
		'id' => 'dam',
		'pattern' => 'http://(?:www\.)?dailymotion\.(?:com|[a-z]{2}|alice\.it)/(?:[^"]*?video|swf)/([a-z0-9]{1,18})',
		'movie' => 'http://www.dailymotion.com/swf/$2&related=0',
		'size' => array(520, 416),
		'ui-height' => 21,
		'lookup-title' => '<h1 class="[^"]+">(.*?)</h1>',
		'fix-html-pattern' => '(?:<div\>)?<object [^>]*><param name="movie" value="$1">.*?</object>(?:<br /><b><a href="$1">[^<]*</a></b>(?:<br /><i>[^<]*<a href="[^"]*">[^<]*</a></i>)?</div\>)?',
	),
	array(
		'id' => 'ggl',
		'pattern' => 'http://video\.google\.(com|com?\.[a-z]{2}|[a-z]{2})/(?:videoplay|url|googleplayer\.swf)\?[^"]*?docid=([\w-]{1,20})',
		'movie' => 'http://video.google.$2/googleplayer.swf?docId=$3',
		'size' => array(400, 326),
		'show-link' => true,
		'lookup-title' => true,
		'fix-html-pattern' => '<embed id="VideoPlayback" src="$1"[^>]*>\s</embed>',
	),
	array(
		'id' => 'gmap',
		'plugin' => 'html',
		'pattern' => '(http://maps\.google\.[^">]+/\w*?\?[^">]+)',
		'movie' => '<iframe class="aext" width="{int:width}" height="{int:height}" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="$1&amp;output=embed"></iframe>',
		'size' => array(425, 350),
		'ui-height' => 0,
		'fix-html-pattern' => '<iframe [^>]+src="$1"></iframe>(?:<br /><small>.*?</small>)?',
		'fix-html-url' => '$1',
	),
	array(
		'id' => 'mcf',
		'pattern' => 'http://(?:www\.)?metacafe\.com/(?:watch|fplayer)/([\w-]{1,20})/',
		'movie' => 'http://www.metacafe.com/fplayer/$2/metacafe.swf',
		'size' => array(400, 345),
		'lookup-title' => '<h2>(.*?)</h2>',
		'fix-html-pattern' => '<embed src="$1"[^>]*>\s</embed>(?:<br><font size = 1>.*?</font>)?',
	),
	array(
		'id' => 'veo',
		'pattern' => 'http://(?:www\.)?veoh\.com/(?:[\w/]*?|videodetails2\.swf\?permalinkId=)(v\d[0-9a-z]*)',
		'movie' => 'http://www.veoh.com/veohplayer.swf?permalinkId=$2&id=anonymous&player=videodetailsembedded&videoAutoPlay=0',
		'size' => array(460, 345),
		'lookup-title' => true,
	),
	array(
		'id' => 'vimeo',
		'pattern' => 'http://(?:www\.|player\.)?vimeo\.com/(?:video/)?(\d{1,12})',
		'movie' => 'http://assets.vimeo.com/flash/moogaloop/5.0.5/moogaloop.swf?v=5.0.5&clip_id=$2&server=vimeo.com&fullscreen=1&show_title=1&show_byline=1&show_portrait=0&color=01AAEA',
		'size' => array(640, 360),
		'fix-html-pattern' => '<object [^>]*>\s{0,3}<param name="allowfullscreen" value="true" />\s{0,3}<param name="allowscriptaccess" value="always" />\s{0,3}<param name="movie" value="http://vimeo\.com/moogaloop\.swf\?clip_id=(\d{1,12})[^<>]*?>.*?</object>(?:<p><a href="http://vimeo\.com.*?</a>.*?</a>.*?</a>\.</p>)?',
		'fix-html-url' => 'http://www.vimeo.com/$1',
		'lookup-title' => true,
		'lookup-title-skip' => true,
	),
	array(
		'id' => 'apple',
		'plugin' => 'quicktime',
		'pattern' => 'http://(?:movies\.apple\.com/movies/(\w+/\w+/[\w\.-]+\.mov)|(?:www\.)?apple\.com/trailers/(\w+/\w+)/?#id(.*?\.mov))',
		'movie' => 'http://movies.apple.com/movies/($2|$3/$4)',
		'size' => array(640, 272),
		'show-link' => true,
		'fix-html-pattern' => '(http://movies\.apple\.com/movies/\w+/\w+/[\w\.-]+\.mov)\?width=(\d+)&(?:amp;)?height=(\d+)',
		'fix-html-url' => '$1#w$2-h$3+16',
		'lookup-url' => 'http://(?:www\.)?apple\.com/trailers/\w+/\w+/?',
		'lookup-pattern' => array('id' => '<a href="http://movies\.apple\.com/movies/\w+/\w+/([\w\.-]+\.mov)(?:\?width=\d+&(?:amp;)?height=\d+)?" class="large">', 'w' => '\?width=(\d+)&(?:amp;)?height=\d+" class="large">', 'h' => '\?width=\d+&(?:amp;)?height=(\d+)" class="large">'),
		'lookup-title' => '<h1>(.*?)</h1>',
	),
	array(
		'id' => 'arc',
		'pattern' => 'http://(?:www\.)?archive\.org/download/([\w-]*?/[\w-]*?\.(?:flv|mp\w|ogv))',
		'movie' => 'http://www.archive.org/flow/FlowPlayerLight.swf?config=%7Bembedded%3Atrue%2CshowFullScreenButton%3Atrue%2CshowMuteVolumeButton%3Atrue%2CshowMenu%3Atrue%2CautoBuffering%3Afalse%2CautoPlay%3Afalse%2CinitialScale%3A%22fit%22%2CmenuItems%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%2Ctrue%2Cfalse%5D%2CusePlayOverlay%3Afalse%2CshowPlayListButtons%3Atrue%2CplayList%3A%5B%7Burl%3A%22$2%22%7D%5D%2CcontrolBarGloss%3A%22high%22%2CshowVolumeSlider%3Atrue%2CbaseURL%3A%22http%3A%2F%2Fwww.archive.org%2Fdownload%2F%22%2Cloop%3Afalse%2CcontrolBarBackgroundColor%3A%220x000000%22%7D',
		'size' => array(480, 360),
		'fix-html-pattern' => '<object [^>]*>\s*<param name="movie" value="http://www\.archive\.org/flow/flowplayer\.commercial-3\.0\.3\.swf" />.*?"url":"([^"]*)".*?</object>',
		'lookup-url' => 'http://(?:www\.)?archive\.org/details/(?:[\w%-]{5,50})',
		'lookup-pattern' => 'IAD\.(?:flv|mp4)s\s=\s\["([\w-]*?/[\w-]*?\.(?:flv|mp\w|ogv))"[],]',
		'lookup-final-url' => 'http://www.archive.org/download/$1',
	),
	array(
		'id' => 'bre',
		'pattern' => '(?:http://embed\.break\.com/(\w+)|http://(?:www\.)?break\.com/[^"]*?\.html#id(\d+))',
		'movie' => 'http://embed.break.com/$2$3',
		'size' => array(464, 392),
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="$1">.*?</object>(?:<br><font size=1>.*?</font>)?',
		'fix-html-url' => '$2',
		'lookup-url' => 'http://(?:www\.)?break\.com/[^"]*?\w+\.html',
		'lookup-pattern' => array('id' => '<meta name="embed_video_url" content="http://embed\.break\.com/(\d+)"'),
	),
	array(
		'id' => 'bri',
		'pattern' => 'http://link\.brightcove\.com/services/(?:link|player)/bcpid(\d+)[^">]*?bctid=?(\d+)',
		'movie' => 'http://services.brightcove.com/services/viewer/federated_f8/$2?videoId=$3&playerId=$2&viewerSecureGatewayURL=https://console.brightcove.com/services/amfgateway&servicesURL=http://services.brightcove.com/services&cdnURL=http://admin.brightcove.com&domain=embed&autoStart=false&',
		'size' => array(486, 412),
		'fix-html-pattern' => '<embed src="http://services.brightcove.com/services/viewer/federated_f8/(\d+)" bgcolor="#FFFFFF" flashVars="videoId=(\d+)[^"]*"[^>]*></embed>',
		'fix-html-url' => 'http://link.brightcove.com/services/link/bcpid$1/bctid$2',
	),
	array(
		'id' => 'esp',
		'pattern' => 'http://(?:sports\.)?espn\.go\.com/(?:broadband/)?(?:player\.swf\?mediaId=|video/videopage\?[^"]*?videoId=|video/clip\?[^"]*?id=)(\d{1,10})',
		'movie' => 'http://sports.espn.go.com/broadband/player.swf?mediaId=$2',
		'size' => array(440, 361),
		'show-link' => true,
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="$1"/><param name="wmode" value="transparent"/><param name="allowScriptAccess" value="always"/><embed src="$1"[^>]*></embed></object>',
		'fix-html-url' => 'http://sports.espn.go.com/broadband/video/videopage?videoId=$2',
	),
	array(
		'id' => 'face',
		'pattern' => 'http://(?:www.)?facebook\.com/video/video\.php\?v=(\w+)',
		'movie' => 'http://www.facebook.com/v/$2',
		'size' => array(480, 360),
		'lookup-url' => 'http://(?:www.)?facebook\.com/video/video\.php\?v=(\w+)(?:&oid=\d+)?',
		'lookup-pattern' => array('w' => '"video_width", "(\d+)"', 'h' => '"video_height", "(\d+)"'),
		'lookup-title' => false,
	),
	array(
		'id' => 'flk',
		'pattern' => 'http://www.flickr.com/photos/[^/]+/(\d+)/?#secret(\w+)',
		'movie' => 'http://www.flickr.com/apps/video/stewart.swf?v=66164&photo_secret=$3&photo_id=$2',
		'size' => array(425, 344),
		'lookup-url' => 'http://www.flickr.com/photos/[^/]+/(\d+)/?',
		'lookup-pattern' => array('secret' => 'photo_secret: \'(\w+)\'', 'w' => 'stewart_go_go_go\((\d+),', 'h' => 'stewart_go_go_go\(\d+, (\d+),'),
	),
	array(
		'id' => 'gam',
		'pattern' => 'http://(?:[a-z]*?\.)?gamespot\.com/[^"]*?video/(?:\d{1,12}/)?(\d{1,12})',
		'movie' => 'http://image.com.com/gamespot/images/cne_flash/production/media_player/proteus/one/proteus2.swf?playerMode=embedded&movieAspect=4.3&flavor=EmbeddedPlayerVersion&skin=http://image.com.com/gamespot/images/cne_flash/production/media_player/proteus/one/skins/gamespot.png&paramsURI=http%3A%2F%2Fwww.gamespot.com%2Fpages%2Fvideo_player%2Fxml.php%3Fid%3D$2%26mode%3Dembedded%26width%3D432%26height%3D362',
		'size' => array(432, 362),
		'show-link' => true,
		'fix-html-pattern' => '<embed [^>]*http%3A%2F%2Fwww\.gamespot\.com%2Fpages%2Fvideo_player%2Fxml\.php%3Fid%3D(\d{1,12})[^>]*/>',
		'fix-html-url' => 'http://uk.gamespot.com/video/$1/',
	),
	array(
		'id' => 'hul',
		'pattern' => '(http://(?:www\.)?hulu\.com/embed/[\w-]{10,32})',
		'movie' => '$2',
		'size' => array(512, 296),
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="$1"></param><embed src="$1"[^<>]*?></embed></object>',
		'lookup-url' => 'http://(?:www\.)?hulu\.com/watch/\d{1,12}/[\w-]{5,50}',
		'lookup-pattern' => '<link\srel="video_src"\shref="(http://(?:www\.)?hulu\.com/embed/[\w-]{10,50})',
		'lookup-title' => true,
	),
	array(
		'id' => 'ign',
		'pattern' => 'http://(?:[a-z0-9]*?\.){0,3}ign\.com/[\w-]*?/objects/(\d{1,10})/(?:[\w-]*?/)?videos/',
		'movie' => 'http://videomedia.ign.com/ev/ev.swf?object_ID=$2',
		'size' => array(433, 360),
		'fix-html-pattern' => '<embed src=\'http://videomedia\.ign\.com/ev/ev\.swf\' flashvars=\'object_ID=(\d{1,10})[^<>]*?></embed>',
		'fix-html-url' => 'http://www.ign.com/dor/objects/$1/videos/',
	),
	array(
		'id' => 'ima',
		'pattern' => 'http://img(\d{1,5})\.imageshack\.us/(?:my\.php\?image=|img\d{1,5}/\d{1,8}/|flvplayer\.swf\?f=T)([\w-]{1,20})\.flv',
		'movie' => 'http://img$2.imageshack.us/flvplayer.swf?f=T$3&autostart=false',
		'size' => array(424, 338),
	),
	array(
		'id' => 'justin',
		'pattern' => 'http://(?:\w{0,3}\.)?justin\.tv/(\w*)',
		'movie' => 'http://www.justin.tv/widgets/jtv_player.swf?channel=$2&auto_play=false',
		'size' => array(468, 383),
		'show-link' => true,
		'show-flashvars' => true,
		'lookup-title' => true,
	),
	array(
		'id' => 'kew',
		'pattern' => 'http://([^/]+)/video/([\w-]{12})\.html#kew',
		'movie' => 'http://$2/p/en/$3.html',
		'size' => array(400, 368),
		'fix-html-pattern' => '<object [^>]*data="http://www\.kewego\.com/swf/p3/epix\.swf\??"[^>]*>.*?</object><div [^>]*><a href="(http://[^/]+/video/[\w-]{12}\.html)">.*?</div></div>',
		'lookup-url' => 'http://[^/]+/video/([\w-]{12})\.html',
		'lookup-title' => true,
		'lookup-pattern' => array('kew' => 'kewego\.com/swf'),
		'lookup-skip-empty' => true,
	),
	array(
		'id' => 'laa',
		'pattern' => 'http://(?:www\.)?(?:last\.fm|lastfm\.[a-z]{2})/music/([^/"\?]+)/_/([\w\+\*%-]*)',
		'movie' => 'http://cdn.last.fm/webclient/s12n/s/5/lfmPlayer.swf?lang=en&lfmMode=playlist&FOD=true&restype=track&artist=$2&resname=$3',
		'size' => array(300, 221),
		'show-link' => true,
		'lookup-title' => '<div id="content">.*?<h1[^>]*>(.*?)</h1>',
	),
	array(
		'id' => 'mgv',
		'pattern' => 'http://(?:www\.)?megavideo\.com/(?:\?[^"]*?v=|v/)([0-9a-z]{8})',
		'movie' => 'http://www.megavideo.com/v/$2.0.0',
		'size' => array(432, 351),
		'fix-html-pattern' => '<object [^>]*><param name="movie" value="$1">.*?</object>',
		'lookup-url' => 'http://(?:www\.)?megavideo\.com/(?:\?[^"]*?d=|d/)([0-9a-z]{8})',
		'lookup-pattern' => 'name="movie" value="(http://www\.megavideo\.com/v/\w+)">',
		'lookup-final-url' => '$1',
		'lookup-title' => false,
	),
	array(
		'id' => 'msn',
		'pattern' => 'http://(soapbox|video)\.msn\.com/(?:video\.aspx)?\?(mkt=[a-z-]{2,7}&(?:amp;)?)?(?:[^"]*?vid=|(?:from=msnvideo&(?:amp;)?showPlaylist=true&(?:amp;)?)?playlist=videoByUuids:uuids:)([0-9a-f-]{8,36})',
		'movie' => 'http://images.$2.msn.com/flash/soapbox1_1.swf?$3ch=&c=v&v=$4&title=false&ifs=true&ad=false',
		'size' => array(432, 364),
		'fix-html-pattern' => '<embed src="http://images\.(?:soapbox|video)\.msn\.com/flash/soapbox1_1\.swf" [^>]*flashvars="c=v&(?:amp;)?v=([0-9a-z]{8}(?:-[0-9a-z]{4}){3}-[0-9a-z]{12})&(?:amp;)?ifs=true&(?:amp;)?fr=msnvideo&(?:amp;)?mkt=en-US&(?:amp;)?brand="></embed>(?:<br /><a href="http://video\.msn\.com/[^<>]*?>[^<>]*?</a>)?',
		'fix-html-url' => 'http://video.msn.com/video.aspx?mkt=en-US&vid=$1',
	),
	array(
		'id' => 'mys',
		'pattern' => 'http://(?:vids\.myspace|myspacetv)\.com/index\.cfm\?[^"]*?VideoID=(\d{1,10})',
		'movie' => 'http://mediaservices.myspace.com/services/media/embed.aspx/m=$2',
		'size' => array(425, 360),
		'fix-html-pattern' => '(?:<a href="http://vids\.myspace\.com/[^"]*">[^<>]*?</a><br/>)?<object width="\d*px" height="\d*px" >.*?myspace.com/services/media/embed.aspx/m=(\d{1,9})[^<>]*?>.*?</object>',
		'fix-html-url' => 'http://vids.myspace.com/index.cfm?fuseaction=vids.individual&videoid=$1',
	),
	array(
		'id' => 'pho',
		'pattern' => 'http://([si](\w{1,5}))\.photobucket\.com/albums/((?:[\w%-]{1,50}/){1,10})(?:\?[^"]*?current=)?([\w%-]{1,50}\.(?:pbr|flv|mp4))',
		'movie' => 'http://$2.photobucket.com/player.swf?file=http://vid$3.photobucket.com/albums/$4$5',
		'size' => array(448, 361),
		'show-link' => true,
	),
	array(
		'id' => 'tin',
		'pattern' => 'http://(?:www\.|\w[\w-]+\.)?tinypic\.com/(?:player\.php\?v=|[rm]/)([0-9a-z-]{1,12})(?:(?:&s=|&amp;s=|/)(\d+))?',
		'movie' => 'http://(v$3|v3).tinypic.com/player.swf?file=$2&s=$3',
		'size' => array(440, 420),
		'fix-html-pattern' => '<embed [^>]*src="http://v(\d+)\.tinypic\.com/player\.swf\?file=([0-9a-z-]{1,12})[^<>]*?>(?:</embed>)?(?:<br><font size="1"><a href="http://tinypic\.com/.*?</font>)?(?:<img style="visibility:hidden;[^<>]*?>)?',
		'fix-html-url' => 'http://tinypic.com/player.php?v=$2&s=$1',
	),
	array(
		'id' => 'yav',
		'pattern' => 'http://(?:(?:www|[a-z]{2})\.)?video\.yahoo\.com/watch/(\d*)/(\d+)(?:#thumb=(http[\w\./%\:]+\.jpg))?',
		'movie' => 'http://d.yimg.com/static.video.yahoo.com/yep/YV_YEP.swf?ver=2.2.40&id=$3&vid=$2&lang=en-us&intl=us&embed=1&thumbUrl=$4',
		'size' => array(512, 322),
		'show-link' => true,
		'fix-html-pattern' => '(?:<div>)?<object [^>]*><param name="movie" value="http://d\.yimg\.com/static\.video\.yahoo\.com/yep/YV_YEP\.swf[^>]*>.*?<param name="flashVars" value="id=(\d+)&(?:amp;)?vid=(\d*)[^>]*thumbUrl=(http[\w\./%]+\.jpg)?[^<>]*>.*?</object>(?:<br /><a href="[^<>]*>.*?</div>)?',
		'fix-html-url' => 'http://video.yahoo.com/watch/$2/$1#thumb=$3',
		'lookup-url' => 'http://(?:(?:www|[a-z]{2})\.)?video\.yahoo\.com/network/[^"]*?(?:v=)?(\d+)',
		'lookup-pattern' => array('id' => '\<a id="nvi_comments_link" href="http://[^"]*?yahoo.com/watch/(\d+/\d+)"', 'thumb=' => '"thumbUrl", "(.*?)"'),
		'lookup-title' => '<h2 id="nvi_title">(.*?)</h2>',
		'lookup-final-url' => 'http://video.yahoo.com/watch/$1',
	),
);
?>